In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
sns.set(color_codes=True) #overide maplot libs ugly colours.
from scipy import stats
from datetime import datetime
from sklearn import preprocessing
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.rcParams['figure.figsize'] = [14, 8] #default figure size
import math
%matplotlib inline

In [2]:
df = pd.read_csv('data\processed_data(by_quarter).csv')

In [3]:
df.drop(['Unnamed: 0', "goal_usd"], axis=1, inplace=True)

In [4]:
df.head()

duration  blurb_length  name_length  usd_pledged  success  US based  \
0  0.163043      0.382353     0.230769     0.000705      1.0       1.0   
1  0.315217      0.676471     0.269231     0.000455      1.0       0.0   
2  0.315217      0.588235     0.230769     0.000129      1.0       1.0   
3  0.478261      0.411765     0.192308     0.000559      1.0       1.0   
4  0.641304      0.411765     0.115385     0.004696      1.0       1.0   

   main_category_comics  main_category_crafts  main_category_dance  \
0                   0.0                   0.0                  0.0   
1                   1.0                   0.0                  0.0   
2                   0.0                   0.0                  0.0   
3                   0.0                   0.0                  0.0   
4                   0.0                   0.0                  0.0   

   main_category_design  ...  main_category_games  main_category_journalism  \
0                   0.0  ...                  1.0                       0.0   
1                   0.0  ...                  0.0                       0.0   
2                   0.0  ...                  0.0                       0.0   
3                   0.0  ...                  0.0                       0.0   
4                   0.0  ...                  0.0                       0.0   

   main_category_music  main_category_photography  main_category_publishing  \
0                  0.0                        0.0                       0.0   
1                  0.0                        0.0                       0.0   
2                  0.0                        0.0                       0.0   
3                  1.0                        0.0                       0.0   
4                  0.0                        0.0                       0.0   

   main_category_technology  main_category_theater  start_Q_Q2  start_Q_Q3  \
0                       0.0                    0.0         0.0         0.0   
1                       0.0                    0.0         0.0         1.0   
2                       0.0                    0.0         1.0         0.0   
3                       0.0                    0.0         0.0         1.0   
4                       1.0                    0.0         0.0         0.0   

   start_Q_Q4  
0         1.0  
1         0.0  
2         0.0  
3         0.0  
4         1.0  

[5 rows x 23 columns]

In [16]:
def random_forest_test(df, y_column,  depth):
    
    import pandas as pd

    # y_column is a string for the column name
    from sklearn.model_selection import train_test_split
    from sklearn.ensemble import RandomForestClassifier

    # define X and y from the dataframe
    y = df[y_column]
    X = df.drop(labels = y_column, axis = 'columns')

    # making the training set and the testing set
    from sklearn.model_selection import train_test_split
    X_train, X_test ,y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

    # Instantiate the estimator
    clf = RandomForestClassifier(max_depth = depth, random_state = 42, n_jobs=-1)

    # Training the model
    clf.fit(X_train, y_train)

    # Making a prediction
    y_pred = clf.predict(X_test)

    # Checking the accuracy
    from sklearn.metrics import accuracy_score
    a_score = accuracy_score(y_test, y_pred)

    # Calculating probability of success
    probability = clf.predict_proba(X_test)

    # Calculate the confusion matrix
    from sklearn.metrics import confusion_matrix
    c_matrix = confusion_matrix(y_test, y_pred)

    # Calculate the classification
    from sklearn.metrics import classification_report
    c_report = classification_report(y_test, y_pred)
    
    #11: KFolds cross validation
    from sklearn.model_selection import cross_val_score
    accuracy = cross_val_score(clf, X_train, y_train, cv = 5)
    print ('KFolds cross validation: \n ', accuracy)
    print ()
    print ('Mean accuracy: \n', accuracy.mean())
    print ()
    
    
    print("Feature Importance: \n", )
    for index, i in enumerate(clf.feature_importances_):
        print (f'Feature {index}: {i:.5}')
    print()
    print("Model: \n",clf)
    print()
    print("y prediction: \n", y_pred)
    print()
    print("Accuracy score: \n", a_score)
    print()
    print("Probability: \n", probability)
    print()
    print("Confusion matrix: \n", c_matrix)
    print()
    print("Classification report: \n", c_report)
    

In [17]:
random_forest_test(df, "success", 5)

KFolds cross validation: 
  [0.87491306 0.87183805 0.86927554 0.86495589 0.87102797]

Mean accuracy: 
 0.8704021014604016

Feature Importance: 

Feature 0: 0.046591
Feature 1: 0.0025003
Feature 2: 0.037679
Feature 3: 0.77195
Feature 4: 0.0015157
Feature 5: 0.010934
Feature 6: 0.0018791
Feature 7: 0.0038827
Feature 8: 0.00018401
Feature 9: 7.1042e-05
Feature 10: 0.00064656
Feature 11: 0.05427
Feature 12: 8.3783e-05
Feature 13: 0.0069227
Feature 14: 0.0083025
Feature 15: 0.0016425
Feature 16: 0.0079043
Feature 17: 0.042473
Feature 18: 0.00016427
Feature 19: 5.8611e-05
Feature 20: 0.00025106
Feature 21: 8.9155e-05

Model: 
 RandomForestClassifier(max_depth=5, n_jobs=-1, random_state=42)

y prediction: 
 [1. 0. 0. ... 0. 1. 0.]

Accuracy score: 
 0.8695601241726703

Probability: 
 [[0.1867527  0.8132473 ]
 [0.71660188 0.28339812]
 [0.79686072 0.20313928]
 ...
 [0.690739   0.309261  ]
 [0.25569782 0.74430218]
 [0.67232146 0.32767854]]

Confusion matrix: 
 [[11641  3261]
 [ 1193 18051]]

Cla

## Optimizing Hyperparameters

In [11]:
def tuning_forest(df, y_column):
    
    import pandas as pd

    # y_column is a string for the column name
    from sklearn.model_selection import train_test_split
    from sklearn.ensemble import RandomForestClassifier

    # define X and y from the dataframe
    y = df[y_column]
    X = df.drop(labels = y_column, axis = 'columns')

    # making the training set and the testing set
    from sklearn.model_selection import train_test_split
    X_train, X_test ,y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

    # Instantiate the estimator
    clf = RandomForestClassifier()

    # Training the model
    clf.fit(X_train, y_train)


    parameters = {'max_depth': list(range(1,5))}

    from sklearn.model_selection import GridSearchCV

    search = GridSearchCV(clf, param_grid= parameters, cv=10)
    search.fit(X_train,y_train)

    print(search.best_score_)
    print(search.best_params_)

In [12]:
tuning_forest(df, 'success')

0.863995735254418
{'max_depth': 4}


In [18]:
random_forest_test(df, 'success',  4)

KFolds cross validation: 
  [0.86660321 0.86685946 0.86462642 0.86078266 0.86524381]

Mean accuracy: 
 0.8648231155969773

Feature Importance: 

Feature 0: 0.068712
Feature 1: 0.0028696
Feature 2: 0.04939
Feature 3: 0.68332
Feature 4: 0.0016855
Feature 5: 0.016047
Feature 6: 0.002082
Feature 7: 0.0065762
Feature 8: 7.5718e-05
Feature 9: 6.1046e-06
Feature 10: 0.000649
Feature 11: 0.072652
Feature 12: 0.00034448
Feature 13: 0.0066736
Feature 14: 0.012461
Feature 15: 0.0014665
Feature 16: 0.012778
Feature 17: 0.061587
Feature 18: 0.00023472
Feature 19: 7.055e-05
Feature 20: 0.0002363
Feature 21: 8.8184e-05

Model: 
 RandomForestClassifier(max_depth=4, n_jobs=-1, random_state=42)

y prediction: 
 [1. 0. 0. ... 0. 1. 0.]

Accuracy score: 
 0.8651672231008024

Probability: 
 [[0.23056793 0.76943207]
 [0.65211064 0.34788936]
 [0.77022026 0.22977974]
 ...
 [0.66623103 0.33376897]
 [0.26687373 0.73312627]
 [0.64392755 0.35607245]]

Confusion matrix: 
 [[11446  3456]
 [ 1148 18096]]

Classifica